{"uuid": "821629e4-03b6-46db-ba7a-a2efde94512b", "children": ["3b06f780-1794-4ec9-84d6-decf0e6a16f0", "034f0ef2-ab04-4ac3-b063-7d0721c2cc45", "b406f76e-bec4-4372-8076-95f1f0be1e2c", "1b76bb5d-6462-4694-9232-4ed67208a4d7", "07a04f29-e565-47bd-8911-f09fa3fa2777", "7d9b5bd1-b4fd-4c21-8a40-7294ebab2e0a", "37c23d50-bd34-4c6d-9968-b0b675e71b10", "19440392-0f68-49bc-bd8c-70a7a192422b", "bb28dde7-6589-4c59-8862-27eb18d36676", "6805ef86-5d4f-4a3e-a730-441fb5dc4e48"], "befores": [{"name": "_Module__pytest_setup_module", "status": "passed", "start": 1618905045416, "stop": 1618905045416}], "afters": [{"name": "_Module__pytest_setup_module::0", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"Sharding column can't be updated CUSTOMER->CUST_ID\")\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 474, in xunit_setup_module_fixture\n    _call_with_optional_argument(teardown_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\Change_MobilePhone_test.py\", line 102, in teardown_module\n    PyMySQL().mysqlupdate('customer',{'cust_id':Change_MobilePhone.initparams['custid']},{'cust_mobile':Change_MobilePhone.initparams['mobile_phone']})\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 76, in mysqlupdate\n    cursor.execute(sql)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 170, in execute\n    result = self._query(query)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 328, in _query\n    conn.query(q)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 517, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 732, in _read_query_result\n    result.read()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 1075, in read\n    first_packet = self.connection._read_packet()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 684, in _read_packet\n    packet.check_error()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\protocol.py\", line 220, in check_error\n    err.raise_mysql_exception(self._data)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\err.py\", line 109, in raise_mysql_exception\n    raise errorclass(errno, errval)\n"}, "start": 1618905066123, "stop": 1618905066161}], "start": 1618905045416, "stop": 1618905066161}