{"name": "是短信登录时，短信验证码验证失败", "status": "broken", "statusDetails": {"message": "AttributeError: 'PyMySQL_EXECUTE' object has no attribute 'args'", "trace": "def setup_module():\n        mobile_phone=LoingSms.initparams['mobile_phone']\n    \n        #1.清除\n        PyMySQL().mysqldel('customer_verify_sms',{'verify_mobile':mobile_phone})\n    \n        #2.插入\n        #vcode='345678'\n        #LoingSms.initparams['vcode']=vcode\n        #已请求参数中的vcode作为构造值\n        vcode=LoingSms.initparams['vcode']\n    \n        now = datetime.datetime.now()\n        now_2=now+datetime.timedelta(days = 1)\n    \n    \n        sql=\"insert into customer_verify_sms(cust_id,verify_mobile,verify_type,verify_code,verify_send_date,\" \\\n            \"verify_date,verify_timeout_date,verify_status,creation_date) \"\\\n                  \"values({},{},{},{},{},{},{},{},{});\".format(0,'\"'+str(mobile_phone)+ '\"',7,'\"'+str(vcode)+ '\"', '\"'+str(now)+ '\"',\n                                                               '\"'+str(now)+ '\"','\"'+str(now_2)+'\"',0,'\"'+str(now)+'\"')\n    \n>       PyMySQL_EXECUTE()(sql)\n\ntestcase\\Loginapi\\Login_Sms_test.py:122: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <utils.pysql.PyMySQL_EXECUTE object at 0x00000000053EB400>\nargs = ('insert into customer_verify_sms(cust_id,verify_mobile,verify_type,verify_code,verify_send_date,verify_date,verify_ti...21-04-26 19:51:37.431667\",\"2021-04-26 19:51:37.431667\",\"2021-04-27 19:51:37.431667\",0,\"2021-04-26 19:51:37.431667\");',)\nkwargs = {}\n\n    def __call__(self,*args,**kwargs):\n>       sql=self.args[0]\nE       AttributeError: 'PyMySQL_EXECUTE' object has no attribute 'args'\n\nutils\\pysql.py:179: AttributeError"}, "parameters": [{"name": "pyfixture", "value": "({'mobile_phone': 18811348250, 'vcode': '999999', 'appkey': '20020001', 'ip_address': '192.199.199.199', 'watchdog_flg': 1, 'permanent_id': 23243242341241231212, 'trace_id': 3234234242342132, 'source_url': 'http://www.ui.com', 'udid': 'abc29088809812121', 'client_version': '10.7.0', 'autokey': None, 'json_info': None, 'tongdun_deviceid': None, 'shumei_deviceid': None, 'result_format': 'json'}, ('-8', '是短信登录时，短信验证码验证失败'))"}], "start": 1619437897703, "stop": 1619437897703, "uuid": "38f9a3dc-247f-49a7-9586-2d577e823059", "historyId": "5a88caa288de1f58f9de877b1417b441", "testCaseId": "3b771a89a9d875ddc678304aa7d66743", "fullName": "testcase.Loginapi.Login_Sms_test#test_LoginSms", "labels": [{"name": "tag", "value": "login_sms"}, {"name": "tag", "value": "flaky(reruns=0, reruns_delay=10)"}, {"name": "parentSuite", "value": "testcase.Loginapi"}, {"name": "suite", "value": "Login_Sms_test"}, {"name": "host", "value": "A06P-A90F12DAA"}, {"name": "thread", "value": "2380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Loginapi.Login_Sms_test"}]}