{"name": "test_Combine[pyfixture4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1018' == 1018", "trace": "pyfixture = ({'custid_child': 11025, 'custid_parent': 50248490, 'loginType': 1, 'merge_channel': 'weixin', ...}, (1018, 'custid %s already bind same type third'))\n\n    @pytest.mark.combine\n    @pytest.mark.flaky(reruns=1, reruns_delay=10)\n    def test_Combine(pyfixture):\n        # 请求\n        url = Combine.url\n        data = pyfixture[0]\n        res = request(url=url, data=data)\n        # print(data)\n>       assert res['return_code'] == pyfixture[1][0]\nE       AssertionError: assert '1018' == 1018\n\ntestcase\\Combineapi\\Combine_test.py:111: AssertionError"}, "parameters": [{"name": "pyfixture", "value": "({'custid_parent': 50248490, 'custid_child': 11025, 'sessionid_parent': 123123123, 'merge_channel': 'weixin', 'loginType': 1, 'result_format': 'json'}, (1018, 'custid %s already bind same type third'))"}], "start": 1611055483526, "stop": 1611055483593, "uuid": "be667b41-79e2-45ee-aa75-7d470bb2f093", "historyId": "6d0671c5dd5b0c018c851e789ec446ef", "testCaseId": "539049fcbb1862a32a91c1f106a060f3", "fullName": "testcase.Combineapi.Combine_test#test_Combine", "labels": [{"name": "tag", "value": "combine"}, {"name": "tag", "value": "flaky(reruns=1, reruns_delay=10)"}, {"name": "parentSuite", "value": "testcase.Combineapi"}, {"name": "suite", "value": "Combine_test"}, {"name": "host", "value": "A06P-A90F12DAA"}, {"name": "thread", "value": "16408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Combineapi.Combine_test"}]}